# Basics of installing PyTorch (CUDA) in Anaconda
- Open Anaconda Powershell Prompt
- Create new virtual environment: `conda create -n py312 python=3.12`
- Activate it: `conda activate py312`
- Install PyTorch using CONDA: `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`
- Verify PyTorch installation: `python -c "import torch; print(torch.__version__)"`
- Verify CUDA availability: `python -c "import torch; print(torch.cuda.is_available())"`
### Alternative PyTorch
- Install PyTorch for CPU: `conda install pytorch torchvision torchaudio cpuonly -c pytorch`

## Tips to redirect your Jupyter Notebook kernel to the new environment
Activate your virtual environment first on Anaconda Powershell Prompt
- #### Install ipykernel
`conda install ipykernel`

- #### Add the environment to Jupyter (e.g. if your virtual environment name is py312)
`python -m ipykernel install --user --name=py312`

In [22]:
# check if PyTorch exists otherwise follow the above steps to install PyTorch

import torch
torch.__version__

'2.5.1'

# Introduction to PyTorch and Tensors
-------------------------------------------
A tensor can be viewed as a multi-dimensional array. Similar to how an n-dimensional vector is shown as a one-dimensional array with _n_ elements relative to a specific basis, any tensor can be expressed as a multi-dimensional array when referenced to a basis. The individual values within this multi-dimensional structure are referred to as the tensor's components.

[PyTorch](https://pytorch.org/foundation) is an open-source machine learning library developed by Facebook's AI Research lab. It's known for its flexibility, intuitive design, and dynamic computational graph which makes debugging easier.
This library offers multi-dimensional tensor data structures and implements various mathematical functions to manipulate these tensors. It also includes numerous tools for effective tensor serialisation, handling arbitrary data types, and provides several other practical utilities.

PyTorch shares significant similarities with NumPy, though it uses the term ''tensor'' instead of ''N-dimensional array''. For example,

In [23]:
import torch
import numpy as np

array_np = np.array([[1, 2, 3],
                    [4, 5, 6]])
array_pytorch = torch.tensor([[1, 2, 3],
                             [4, 5, 6]])
print(array_np)
print(array_pytorch)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


Now let us create tensors and do some operations in PyTorch.

In [24]:
# create specific tensors
zeros = torch.zeros(3, 4)  # 3x4 tensor of zeros
ones = torch.ones(2, 3)    # 2x3 tensor of ones
rand = torch.rand(2, 2)    # 2x2 tensor of random numbers (0-1)

In [25]:
# Create a 2x3 tensor
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a.shape  # dimension of the tensor a

torch.Size([2, 3])

In [26]:
# Create tensor b of the same shape with tensor a
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
# Add the tensors
result = a + b
print(result)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


In [27]:
# Create two 2x2 matrices
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
# Perform matrix multiplication using torch.matmul
matrix_mult_result = torch.matmul(matrix_a, matrix_b)
print(matrix_mult_result)

tensor([[19, 22],
        [43, 50]])


In [28]:
# Create two 1D tensors (vectors)
vector_a = torch.tensor([1, 2, 3])
vector_b = torch.tensor([4, 5, 6])
# Computing the dot product between two vectors using torch.dot
dot_product_result = torch.dot(vector_a, vector_b)
print(dot_product_result)

tensor(32)


In this section, we have introduced some basic tensor operations.
To learn more about tensor operations, refer to the official documentation:
[Tensor Operations](https://pytorch.org/docs/stable/tensors.html)